carsAPI:
  host: "car-booking-proc-api.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  client_id: "52b3ae7d19ec4911919fce85c4ec2b6c"
  client_secret: "6c80B07938584d32b2F48cee7Be45954"
  basePath: "/procapi/"
  
hotelsAPI:
  host: "hotel-booking-prc-app.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basePath: "/api/hotels"
  reconnectionCount: "5000"
  reconnectionTime: "3"
  clientID: "6733a9fb041449ec9556370c3e2af025"
  clientSecret: "ba94BbB887cb4145930A586028ADA52d"
  
flight:
  host: "process-flight-api.us-e2.cloudhub.io"
  port: "80"
  timeout: "10000"
  basePath: "/procapi"
  reconnectionCount: "5000"
  reconnectionTime: "3"
  clientID: "8cc5eefc77b545a7beb141eacf8fa11f"
  clientSecret: "9Ae452D7b7964e92A4768810bDc9B230"
  
json:
  logger:
    application:
      version: "1.0.0"
      name: "bookmyholiday-exp-api"